### ISSUE TITLE
Python remote control unusable, problem during init - error while accessing redpitaya memory (Bus error) ?

### ISSUE THREAD

**Issue by BertheGrandPied** [marceluda/rp_lock-in_pid_h#2]
Hello,

i have a problem trying using python to remote control the app. I was using the example and when trying to use red_pitaya_app init function it crash. I will do short, there was a problem when executing the `/opt/redpitaya/www/apps/lock_in+pid_harmonic/py/osc.py` function on the RedPitaya in order to get the regs list, the array received was empty (SSH was fine, and connexion was established, the remote command was send).

So I take a look to osc.py on the redPitaya try to find the source of problems, when executing the script it throw me a bus error... I have the impresson that the error is when calling osc.show() function from hugo.py of the class `fpga-regs`.
In this function, everything is fine in the begining, i can print the list of regs, but it start to fail when trying to execute the function `val()` of the fpga-reg object. when doing so, a bus error appears.

Taking a look to this val() function, the `/dev/mem` looks correctly open by `mmap`. The bus error appears when trying to read a memory block from `mem` object return by `mmap`... Si I am kind of lost, I don't understand why on my redpitaya crash when trying to read the `/dev/mem` file.

Do you have any ideas ? Is there a piece of config to do on the linux system running on the redPitaya (I saw nothing about it on redPitaya documentation)

Regards,

L.D

**Comment by BertheGrandPied** [comment]
Sorry, my mistake, it's solved. I forget to start the app before using my Python, that was really stupid.

L.D

**Comment by dzzzz0617** [comment]
> Sorry, my mistake, it's solved. I forget to start the app before using my Python, that was really stupid.
> 
> L.D

**Comment by dzzzz0617** [comment]
> Sorry, my mistake, it's solved. I forget to start the app before using my Python, that was really stupid.
> 
> L.D
Hello,
I have the same problem in using SSH connection . This problem has bothered me for a long time, could you help me

**Comment by dzzzz0617** [comment]
> Sorry, my mistake, it's solved. I forget to start the app before using my Python, that was really stupid.
> 
> L.D

what does it mean to start the app , how to operate , I urgently need your help

**Comment by marceluda** [comment]
It means to open it on the browser for the first time, I suppose .

**Comment by BertheGrandPied** [comment]
Good afternoon,

Yes Mr Marceluda is right, that mean to start the app through the browser or with SSH (in order to load the .bit) and the browser can be not needed in fact (you load the .bit using the cat command like : `cat path_fpga_config > /dev/xdevcfg`).

I actually work on modified version of Mr Marceluda code on the fpga and custom remote control for long time now so I less familiar on how it works (I don't remember), sorry to not be able to be more specific.

if I got some more specific, I will post them here. 

Regards,

L.D

**Comment by marceluda** [comment]
It's hard for me to keep maintaining the project code.

But if you make a new interface, remote control system or whatever and want
to publish it, please let me know. I can upload it to this repo or put the
link to your repo.

**Comment by dzzzz0617** [comment]
Thank yours advice.

But i still no solve this problem, it makes me sad. I tried your way through open app on the browser and SSH enter Linux shell executing  `cat /opt/redpitaya/www/apps/lock_in+pid_harmonic/red_pitaya.bit > /dev/xdevcfg`  before using python to red_pitaya_app init function, but still the same mistake.

> ~\Desktop\rp_lock-in_pid_h-master\rp_lock-in_pid_h-master\resources\remote_control\shh_version\control_hugo.py in load(self)
>     302         self.parent.log('rp.'+self.name+'.load(): '+self.cmd )
>     303         for rta in self.parent.ssh_cmd(self.cmd).strip().split('\n'):
> --> 304             self.data[ rta.strip().split(':')[0].strip() ] = int(rta.strip().split(':')[1].strip())
> IndexError: list index out of range

I'm at the edge of collapse.Eager for your help. 
![erro](https://user-images.githubusercontent.com/100478323/160528169-89a01382-bbd1-48e9-b182-877c0731ea31.png)

**Comment by marceluda** [comment]
I still can't understand your particular error. Your image doesn't help
me...

Please... write to me at my PERSONAL mail and I will try to help you a bit
more. But I don't promise anything.

https://marceluda.github.io/rp_lock-in_pid/help/contact/
