### ISSUE TITLE
Phase in oscillator

### ISSUE THREAD

**Issue by Gacosta2** [marceluda/rp_lock-in_pid_h#4]
Hello my group is trying to use this as a standalone laser controller with the Lock-in and PID. Could you point me in the direction of the code that creates the reference signals? I would like to have the X and Y values become phase-dependant.

**Comment by marceluda** [comment]
Hello Gacosta.

The easiest way to do that is to use cos_1f signal for modulation. The, X
and Y will demodulate using cos_ref and sin_ref , which hace a phase
relation with  cos_1f.

Are you using the "Lock-in+PID" App (
https://marceluda.github.io/rp_lock-in_pid/ ) or "Harmonic Lock-in+PID" App
?

If you really want to get to the code you have to look at the lock-in
module (
https://github.com/marceluda/rp_lock-in_pid/blob/master/lock_in%2Bpid/fpga/rtl/lock.v
) and the function generator module (
https://github.com/marceluda/rp_lock-in_pid/blob/master/lock_in%2Bpid/fpga/rtl/lock/gen_mod2.v
). Or in the most recent App,
https://github.com/marceluda/rp_lock-in_pid_h/blob/master/lock_in%2Bpid_harmonic/fpga/rtl/lock.v
|
https://github.com/marceluda/rp_lock-in_pid_h/blob/master/lock_in%2Bpid_harmonic/fpga/rtl/lock/gen_mod_h.v


I hope this helps.

This App is based in an old version of Scope App ... and the development
tools you should have to implement it are described here:
https://github.com/RedPitaya/RedPitaya/tree/release-v0.95

**Comment by Gacosta2** [comment]
Yes, I am using the Harmonic Lock-in application.  I attempted to use the F1o signal as the error signal, as that is what I saw in your paper had a phase dependence,  however the actual signal did not give any kind of derivative signal from the SAS peaks that were put into the Pitaya.  

I'll look into the code thanks for the tips, much appreciated.
